build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=some-file'
                coverage:
                    file: 'some-file'
                    format: 'clover'
    environment:
        php: '5.5.25'
    nodes:
        php54:
            environment:
                php: 5.4.41
        php55:
            environment:
                php: 5.5.25
        php56:
            environment:
                php: 5.6.9
        php70:
            environment:
                php: 7.0.20
        php71:
            environment:
                php: 7.1.6
